// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpecTechApp.Data;

namespace SpecTechApp.Migrations
{
    [DbContext(typeof(TechContext))]
    [Migration("20210315144237_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpecTechApp.Models.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TechId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TechId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("SpecTechApp.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d12665e-7b9f-4625-b450-e20825c5b6bd"),
                            Name = "Заказчик"
                        },
                        new
                        {
                            Id = new Guid("e5df3611-1e64-420d-87d6-d408b1434481"),
                            Name = "Исполнитель"
                        },
                        new
                        {
                            Id = new Guid("f1e4e859-aa75-4b31-9f1c-132621172160"),
                            Name = "Система"
                        },
                        new
                        {
                            Id = new Guid("a67fee06-72a8-469f-a615-aba1baf361b3"),
                            Name = "Администратор"
                        });
                });

            modelBuilder.Entity("SpecTechApp.Models.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("406da934-8d82-4874-bb77-ebd698ce6e0b"),
                            Name = "Создано"
                        },
                        new
                        {
                            Id = new Guid("7f6da3cb-54a4-4385-a1d4-bacdc89fcb6d"),
                            Name = "Поиск"
                        },
                        new
                        {
                            Id = new Guid("8cf2c3f4-fb6f-4dd2-a942-476b92665cee"),
                            Name = "Предложено"
                        },
                        new
                        {
                            Id = new Guid("5e719636-110d-4e09-8bc8-f21ffad6fb4e"),
                            Name = "Отказано"
                        },
                        new
                        {
                            Id = new Guid("fff4691e-43b4-42de-b8a1-656705967d7c"),
                            Name = "Отмена"
                        },
                        new
                        {
                            Id = new Guid("7630cad8-6eed-4e06-8a73-3d0aa2fbce99"),
                            Name = "В работе"
                        },
                        new
                        {
                            Id = new Guid("56fc39c1-41c1-484b-8e65-d32f9a403b42"),
                            Name = "Выполнено"
                        });
                });

            modelBuilder.Entity("SpecTechApp.Models.Tech", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GovNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeOfTechId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TypeOfTechId");

                    b.ToTable("Techs");
                });

            modelBuilder.Entity("SpecTechApp.Models.TypeOfTech", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeOfTech");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30fe6c87-4123-4ac4-9f95-f2788cd2b92b"),
                            Name = "Кран"
                        },
                        new
                        {
                            Id = new Guid("a957cce7-6b25-4050-9bf9-2eb27d7d71ce"),
                            Name = "Грузовик"
                        },
                        new
                        {
                            Id = new Guid("c67dff8e-b2e7-4068-a7f0-5130619f7130"),
                            Name = "Бульдозер"
                        },
                        new
                        {
                            Id = new Guid("516d3ca0-4bdb-488b-a1cb-fcb0174127d3"),
                            Name = "Трактор"
                        },
                        new
                        {
                            Id = new Guid("62abd389-1276-42bd-a6ef-1960ca184258"),
                            Name = "Газель"
                        });
                });

            modelBuilder.Entity("SpecTechApp.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SpecTechApp.Models.Quest", b =>
                {
                    b.HasOne("SpecTechApp.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpecTechApp.Models.Tech", "Tech")
                        .WithMany()
                        .HasForeignKey("TechId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Tech");
                });

            modelBuilder.Entity("SpecTechApp.Models.Tech", b =>
                {
                    b.HasOne("SpecTechApp.Models.TypeOfTech", "TypeofTech")
                        .WithMany()
                        .HasForeignKey("TypeOfTechId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeofTech");
                });

            modelBuilder.Entity("SpecTechApp.Models.User", b =>
                {
                    b.HasOne("SpecTechApp.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
